/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Mercoa from "../../../../api/index";
import * as core from "../../../../core";
import { CurrencyCode } from "../../paymentMethodTypes/types/CurrencyCode";

export const InvoiceLineItemResponse: core.serialization.ObjectSchema<
    serializers.InvoiceLineItemResponse.Raw,
    Mercoa.InvoiceLineItemResponse
> = core.serialization.object({
    id: core.serialization.string(),
    amount: core.serialization.number().optional(),
    currency: CurrencyCode,
    description: core.serialization.string().optional(),
    name: core.serialization.string().optional(),
    quantity: core.serialization.number().optional(),
    unitPrice: core.serialization.number().optional(),
    serviceStartDate: core.serialization.date().optional(),
    serviceEndDate: core.serialization.date().optional(),
    metadata: core.serialization.record(core.serialization.string(), core.serialization.string()).optional(),
    glAccountId: core.serialization.string().optional(),
    createdAt: core.serialization.date(),
    updatedAt: core.serialization.date(),
});

export declare namespace InvoiceLineItemResponse {
    interface Raw {
        id: string;
        amount?: number | null;
        currency: CurrencyCode.Raw;
        description?: string | null;
        name?: string | null;
        quantity?: number | null;
        unitPrice?: number | null;
        serviceStartDate?: string | null;
        serviceEndDate?: string | null;
        metadata?: Record<string, string> | null;
        glAccountId?: string | null;
        createdAt: string;
        updatedAt: string;
    }
}
