/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Mercoa from "../../../../api/index";
import * as core from "../../../../core";
import { InvoiceRequest } from "./InvoiceRequest";

export const InvoiceCreationRequest: core.serialization.ObjectSchema<
    serializers.InvoiceCreationRequest.Raw,
    Mercoa.InvoiceCreationRequest
> = core.serialization.object({}).extend(InvoiceRequest);

export declare namespace InvoiceCreationRequest {
    interface Raw extends InvoiceRequest.Raw {}
}
