/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Mercoa from "../../../../api/index";
import * as core from "../../../../core";

export const InvoiceStatus: core.serialization.Schema<serializers.InvoiceStatus.Raw, Mercoa.InvoiceStatus> =
    core.serialization.enum_([
        "UNASSIGNED",
        "DRAFT",
        "NEW",
        "APPROVED",
        "SCHEDULED",
        "PENDING",
        "PAID",
        "ARCHIVED",
        "REFUSED",
        "CANCELED",
        "FAILED",
    ]);

export declare namespace InvoiceStatus {
    export type Raw =
        | "UNASSIGNED"
        | "DRAFT"
        | "NEW"
        | "APPROVED"
        | "SCHEDULED"
        | "PENDING"
        | "PAID"
        | "ARCHIVED"
        | "REFUSED"
        | "CANCELED"
        | "FAILED";
}
