/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Mercoa from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { CheckPaymentDestinationOptions } from "./CheckPaymentDestinationOptions.js";
import { BankAccountPaymentDestinationOptions } from "./BankAccountPaymentDestinationOptions.js";
import { UtilityPaymentDestinationOptions } from "./UtilityPaymentDestinationOptions.js";
import { CustomPaymentDestinationOptions } from "./CustomPaymentDestinationOptions.js";

export const PaymentDestinationOptions: core.serialization.Schema<
    serializers.PaymentDestinationOptions.Raw,
    Mercoa.PaymentDestinationOptions
> = core.serialization
    .union("type", {
        check: CheckPaymentDestinationOptions,
        bankAccount: BankAccountPaymentDestinationOptions,
        utility: UtilityPaymentDestinationOptions,
        custom: CustomPaymentDestinationOptions,
    })
    .transform<Mercoa.PaymentDestinationOptions>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace PaymentDestinationOptions {
    export type Raw =
        | PaymentDestinationOptions.Check
        | PaymentDestinationOptions.BankAccount
        | PaymentDestinationOptions.Utility
        | PaymentDestinationOptions.Custom;

    export interface Check extends CheckPaymentDestinationOptions.Raw {
        type: "check";
    }

    export interface BankAccount extends BankAccountPaymentDestinationOptions.Raw {
        type: "bankAccount";
    }

    export interface Utility extends UtilityPaymentDestinationOptions.Raw {
        type: "utility";
    }

    export interface Custom extends CustomPaymentDestinationOptions.Raw {
        type: "custom";
    }
}
