/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Mercoa from "../../../index";

/**
 * @example
 *     {
 *         jobId: "cntgen_d6734204-ae46-4fe9-a0c5-bd2763d40c9b",
 *         contract: {
 *             id: "cnt_3bd62b69-3835-433e-829f-4388a2e46c41",
 *             summary: "Contract Start Date: January 29, 2025\nParties to the Agreement:\n- Provider (Vendor): [Vendor Name] - Client (Payer): [Client Name]\nFees and Payment Terms:\n- Monthly Recurring Fee: \\$20.00 - Payment Schedule: Fees are payable in advance on the 1st day of each month. - First Payment Date: February 1, 2025 - Payment Method: Via credit card to the account designated by Provider. - Payment Due Date: Payment is due 5 days after the invoice date.\n",
 *             recurrences: [{
 *                     id: "cntrec_0b2d48a7-38e8-44e1-9abc-95e0e67eb484",
 *                     contractId: "cnt_3bd62b69-3835-433e-829f-4388a2e46c41",
 *                     rrule: "DTSTART:20250201T000000ZRRULE:FREQ=MONTHLY;INTERVAL=1;BYMONTHDAY=1",
 *                     justification: "Monthly recurring fee billed in advance on the 1st of each month",
 *                     filteredContractSummary: "Contract Start Date: January 29, 2025\nParties to the Agreement:\n- Provider (Vendor): [Vendor Name] - Client (Payer): [Client Name]\nFees and Payment Terms:\n- Monthly Recurring Fee: \\$20.00 - Payment Schedule: Fees are payable in advance on the 1st day of each month. - First Payment Date: February 1, 2025 - Payment Method: Via credit card to the account designated by Provider. - Payment Due Date: Payment is due 5 days after the invoice date.\n",
 *                     invoiceSchema: {
 *                         lineItems: [{
 *                                 name: "Monthly Subscription Service Fee",
 *                                 unitPrice: 20,
 *                                 currency: Mercoa.CurrencyCode.Usd,
 *                                 quantity: 1
 *                             }]
 *                     },
 *                     createdInvoiceIds: ["in_8545a84e-a45f-41bf-bdf1-33b42a55812c"],
 *                     createdAt: "2025-01-29T00:00:00Z",
 *                     updatedAt: "2025-01-29T00:00:00Z"
 *                 }],
 *             nextInvoiceDate: "2025-03-01",
 *             creatorEntityId: "ent_8545a84e-a45f-41bf-bdf1-33b42a55812c",
 *             payerId: "ent_8545a84e-a45f-41bf-bdf1-33b42a55812c",
 *             payer: {
 *                 id: "ent_8545a84e-a45f-41bf-bdf1-33b42a55812c",
 *                 foreignId: "MY-DB-ID-12345",
 *                 name: "Acme Inc.",
 *                 email: "customer@acme.com",
 *                 acceptedTos: true,
 *                 status: Mercoa.EntityStatus.Verified,
 *                 isCustomer: true,
 *                 isPayor: true,
 *                 isPayee: false,
 *                 isNetworkPayor: false,
 *                 isNetworkPayee: false,
 *                 accountType: Mercoa.AccountType.Business,
 *                 updatedAt: "2024-01-02T00:00:00Z",
 *                 createdAt: "2024-01-01T00:00:00Z",
 *                 profile: {
 *                     business: {
 *                         email: "customer@acme.com",
 *                         legalBusinessName: "Acme Inc.",
 *                         businessType: Mercoa.BusinessType.Llc,
 *                         phone: {
 *                             countryCode: "1",
 *                             number: "4155551234"
 *                         },
 *                         address: {
 *                             addressLine1: "123 Main St",
 *                             addressLine2: "Unit 1",
 *                             city: "San Francisco",
 *                             stateOrProvince: "CA",
 *                             postalCode: "94105",
 *                             country: "US"
 *                         },
 *                         taxIdProvided: true,
 *                         taxId: {
 *                             ein: {
 *                                 number: "12-3456789"
 *                             }
 *                         },
 *                         ownersProvided: true
 *                     }
 *                 },
 *                 accounts: [{
 *                         accountId: "85866843",
 *                         postalCode: "94105",
 *                         nameOnAccount: "John Doe"
 *                     }],
 *                 paymentMethods: [{
 *                         type: "bankAccount",
 *                         id: "pm_4794d597-70dc-4fec-b6ec-c5988e759769",
 *                         accountName: "My Checking Account",
 *                         bankName: "Chase",
 *                         routingNumber: "12345678",
 *                         accountNumber: "99988767623",
 *                         accountType: Mercoa.BankType.Checking,
 *                         status: Mercoa.BankStatus.Verified,
 *                         isDefaultSource: true,
 *                         isDefaultDestination: true,
 *                         supportedCurrencies: [Mercoa.CurrencyCode.Usd],
 *                         metadata: {},
 *                         frozen: false,
 *                         createdAt: "2021-01-01T00:00:00Z",
 *                         updatedAt: "2021-01-01T00:00:00Z"
 *                     }],
 *                 counterpartyType: [Mercoa.CounterpartyNetworkType.Entity]
 *             },
 *             vendorId: "ent_21661ac1-a2a8-4465-a6c0-64474ba8181d",
 *             vendor: {
 *                 id: "ent_21661ac1-a2a8-4465-a6c0-64474ba8181d",
 *                 foreignId: "MY-DB-ID-90909",
 *                 name: "Big Box Store",
 *                 email: "vendor@bigboxstore.com",
 *                 acceptedTos: false,
 *                 status: Mercoa.EntityStatus.Unverified,
 *                 isCustomer: false,
 *                 isPayor: false,
 *                 isPayee: true,
 *                 isNetworkPayor: false,
 *                 isNetworkPayee: false,
 *                 accountType: Mercoa.AccountType.Business,
 *                 updatedAt: "2024-01-02T00:00:00Z",
 *                 createdAt: "2024-01-01T00:00:00Z",
 *                 profile: {
 *                     business: {
 *                         email: "vendor@bigboxstore.com",
 *                         legalBusinessName: "Big Box Store",
 *                         businessType: Mercoa.BusinessType.PublicCorporation,
 *                         taxIdProvided: false,
 *                         ownersProvided: false
 *                     }
 *                 },
 *                 paymentMethods: [{
 *                         type: "bankAccount",
 *                         id: "pm_7610541f-4619-4033-8620-cfccfb811293",
 *                         accountName: "Vendor Checking Account",
 *                         bankName: "Chase",
 *                         routingNumber: "66554433",
 *                         accountNumber: "55934059697648",
 *                         accountType: Mercoa.BankType.Checking,
 *                         status: Mercoa.BankStatus.New,
 *                         isDefaultSource: true,
 *                         isDefaultDestination: true,
 *                         supportedCurrencies: [Mercoa.CurrencyCode.Usd],
 *                         metadata: {},
 *                         frozen: false,
 *                         createdAt: "2021-01-01T00:00:00Z",
 *                         updatedAt: "2021-01-01T00:00:00Z"
 *                     }],
 *                 counterpartyType: [Mercoa.CounterpartyNetworkType.Entity]
 *             },
 *             createdAt: "2025-01-29T00:00:00Z",
 *             updatedAt: "2025-02-01T00:00:00Z"
 *         }
 *     }
 */
export interface GenerateContractResponse {
    /** Job ID */
    jobId: Mercoa.ContractJobId;
    /** Contract */
    contract: Mercoa.ContractResponse;
}
