/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Mercoa } from "@mercoa/javascript";
import * as core from "../../../../core";

export const ApproverResponse: core.serialization.ObjectSchema<
    serializers.ApproverResponse.Raw,
    Mercoa.ApproverResponse
> = core.serialization
    .object({
        user: core.serialization.lazyObject(async () => (await import("../../..")).EntityUserResponse).optional(),
    })
    .extend(core.serialization.lazyObject(async () => (await import("../../..")).Approver));

export declare namespace ApproverResponse {
    interface Raw extends serializers.Approver.Raw {
        user?: serializers.EntityUserResponse.Raw | null;
    }
}
