/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Mercoa from "../../../index.js";

/**
 * @example
 *     {
 *         achStandard: {
 *             type: "flat",
 *             amount: 2.5
 *         },
 *         achSameDay: {
 *             type: "percentage",
 *             amount: 2.5
 *         },
 *         checkPrint: {
 *             type: "flat",
 *             amount: 2.5
 *         },
 *         checkMail: {
 *             type: "flat",
 *             amount: 2.5
 *         },
 *         checkMailPriority: {
 *             type: "flat",
 *             amount: 2.5
 *         },
 *         checkMailUpsNextDay: {
 *             type: "flat",
 *             amount: 2.5
 *         }
 *     }
 */
export interface FeeCustomizationRailRequest {
    /** The fee for the ACH standard rail. */
    achStandard?: Mercoa.PaymentMethodFee;
    /** The fee for the ACH same day rail. */
    achSameDay?: Mercoa.PaymentMethodFee;
    /** The fee for the check print rail. */
    checkPrint?: Mercoa.PaymentMethodFee;
    /** The fee for the check mail rail. */
    checkMail?: Mercoa.PaymentMethodFee;
    /** The fee for the check mail priority rail. */
    checkMailPriority?: Mercoa.PaymentMethodFee;
    /** The fee for the check mail UPS next day rail. */
    checkMailUpsNextDay?: Mercoa.PaymentMethodFee;
}
