/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Mercoa from "../../../index";

/**
 * @example
 *     {
 *         remainingAmount: 50,
 *         currency: Mercoa.CurrencyCode.Usd,
 *         vendorCredits: [{
 *                 id: "vcr_c3f4c87d-794d-4543-9562-575cdddfc0d7",
 *                 totalAmount: 100,
 *                 remainingAmount: 0,
 *                 currency: Mercoa.CurrencyCode.Usd,
 *                 vendorId: "ent_21661ac1-a2a8-4465-a6c0-64474ba8181d",
 *                 payerId: "ent_8545a84e-a45f-41bf-bdf1-33b42a55812c",
 *                 creatorEntityId: "ent_21661ac1-a2a8-4465-a6c0-64474ba8181d",
 *                 note: "This is a note",
 *                 invoiceIds: ["in_26e7b5d3-a739-4b23-9ad9-6aaa085f47a9"],
 *                 createdAt: "2021-01-01T00:00:00Z",
 *                 updatedAt: "2021-01-01T00:00:00Z"
 *             }]
 *     }
 */
export interface CalculateVendorCreditUsageResponse {
    /** Remaining amount on the invoice after vendor credits are applied in major units. */
    remainingAmount: number;
    /** Currency code for the amount. Defaults to USD. */
    currency: Mercoa.CurrencyCode;
    /** Vendor credits that will be applied to the invoice. The objects returned represent the states each vendor credit will be in AFTER they are applied to the invoice, not their current states. */
    vendorCredits: Mercoa.VendorCreditResponse[];
}
