/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Mercoa from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const OcrCustomizationRequest: core.serialization.ObjectSchema<
    serializers.OcrCustomizationRequest.Raw,
    Mercoa.OcrCustomizationRequest
> = core.serialization.object({
    lineItems: core.serialization.boolean().optional(),
    collapseLineItems: core.serialization.boolean().optional(),
    invoiceMetadata: core.serialization.boolean().optional(),
    lineItemMetadata: core.serialization.boolean().optional(),
    lineItemGlAccountId: core.serialization.boolean().optional(),
    predictMetadata: core.serialization.boolean().optional(),
    taxAndShippingAsLineItems: core.serialization.boolean().optional(),
    splitDocuments: core.serialization.boolean().optional(),
});

export declare namespace OcrCustomizationRequest {
    export interface Raw {
        lineItems?: boolean | null;
        collapseLineItems?: boolean | null;
        invoiceMetadata?: boolean | null;
        lineItemMetadata?: boolean | null;
        lineItemGlAccountId?: boolean | null;
        predictMetadata?: boolean | null;
        taxAndShippingAsLineItems?: boolean | null;
        splitDocuments?: boolean | null;
    }
}
