/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Mercoa from "../../../index";

/**
 * @example
 *     {
 *         type: "bankAccountToBankAccount",
 *         id: "trx_bb08e72f-19f8-45f3-bcf9-46fdc46cb2f4",
 *         status: Mercoa.TransactionStatus.Pending,
 *         amount: 10000,
 *         currency: "USD",
 *         payerId: "ent_bb08e72f-19f8-45f3-bcf9-46fdc46cb2f4",
 *         payer: {
 *             id: "ent_8545a84e-a45f-41bf-bdf1-33b42a55812c",
 *             foreignId: "MY-DB-ID-12345",
 *             name: "Acme Inc.",
 *             email: "customer@acme.com",
 *             acceptedTos: true,
 *             status: Mercoa.EntityStatus.Verified,
 *             isCustomer: true,
 *             isPayor: true,
 *             isPayee: false,
 *             isNetworkPayor: false,
 *             isNetworkPayee: false,
 *             accountType: Mercoa.AccountType.Business,
 *             updatedAt: "2024-01-02T00:00:00Z",
 *             createdAt: "2024-01-01T00:00:00Z",
 *             profile: {
 *                 business: {
 *                     email: "customer@acme.com",
 *                     legalBusinessName: "Acme Inc.",
 *                     businessType: Mercoa.BusinessType.Llc,
 *                     phone: {
 *                         countryCode: "1",
 *                         number: "4155551234"
 *                     },
 *                     address: {
 *                         addressLine1: "123 Main St",
 *                         addressLine2: "Unit 1",
 *                         city: "San Francisco",
 *                         stateOrProvince: "CA",
 *                         postalCode: "94105",
 *                         country: "US"
 *                     },
 *                     taxIdProvided: true,
 *                     taxId: {
 *                         ein: {
 *                             number: "12-3456789"
 *                         }
 *                     },
 *                     ownersProvided: true
 *                 }
 *             },
 *             accounts: [{
 *                     accountId: "85866843",
 *                     postalCode: "94105",
 *                     nameOnAccount: "John Doe"
 *                 }],
 *             paymentMethods: [{
 *                     type: "bankAccount",
 *                     id: "pm_4794d597-70dc-4fec-b6ec-c5988e759769",
 *                     accountName: "My Checking Account",
 *                     bankName: "Chase",
 *                     routingNumber: "12345678",
 *                     accountNumber: "99988767623",
 *                     accountType: Mercoa.BankType.Checking,
 *                     status: Mercoa.BankStatus.Verified,
 *                     isDefaultSource: true,
 *                     isDefaultDestination: true,
 *                     supportedCurrencies: [Mercoa.CurrencyCode.Usd],
 *                     metadata: {},
 *                     frozen: false,
 *                     createdAt: "2021-01-01T00:00:00Z",
 *                     updatedAt: "2021-01-01T00:00:00Z"
 *                 }],
 *             counterpartyType: [Mercoa.CounterpartyNetworkType.Entity]
 *         },
 *         paymentSource: {
 *             type: "bankAccount",
 *             id: "pm_4794d597-70dc-4fec-b6ec-c5988e759769",
 *             accountName: "My Checking Account",
 *             bankName: "Chase",
 *             routingNumber: "12345678",
 *             accountNumber: "99988767623",
 *             accountType: Mercoa.BankType.Checking,
 *             status: Mercoa.BankStatus.Verified,
 *             isDefaultSource: true,
 *             isDefaultDestination: true,
 *             supportedCurrencies: [Mercoa.CurrencyCode.Usd],
 *             metadata: {},
 *             frozen: false,
 *             createdAt: "2021-01-01T00:00:00Z",
 *             updatedAt: "2021-01-01T00:00:00Z"
 *         },
 *         paymentSourceId: "pm_65523ab0-043d-4706-b2b2-0b73fed92269",
 *         vendorId: "ent_bb08e72f-19f8-45f3-bcf9-46fdc46cb2f4",
 *         vendor: {
 *             id: "ent_21661ac1-a2a8-4465-a6c0-64474ba8181d",
 *             foreignId: "MY-DB-ID-90909",
 *             name: "Big Box Store",
 *             email: "vendor@bigboxstore.com",
 *             acceptedTos: false,
 *             status: Mercoa.EntityStatus.Unverified,
 *             isCustomer: false,
 *             isPayor: false,
 *             isPayee: true,
 *             isNetworkPayor: false,
 *             isNetworkPayee: false,
 *             accountType: Mercoa.AccountType.Business,
 *             updatedAt: "2024-01-02T00:00:00Z",
 *             createdAt: "2024-01-01T00:00:00Z",
 *             profile: {
 *                 business: {
 *                     email: "vendor@bigboxstore.com",
 *                     legalBusinessName: "Big Box Store",
 *                     businessType: Mercoa.BusinessType.PublicCorporation,
 *                     taxIdProvided: false,
 *                     ownersProvided: false
 *                 }
 *             },
 *             paymentMethods: [{
 *                     type: "bankAccount",
 *                     id: "pm_7610541f-4619-4033-8620-cfccfb811293",
 *                     accountName: "Vendor Checking Account",
 *                     bankName: "Chase",
 *                     routingNumber: "66554433",
 *                     accountNumber: "55934059697648",
 *                     accountType: Mercoa.BankType.Checking,
 *                     status: Mercoa.BankStatus.New,
 *                     isDefaultSource: true,
 *                     isDefaultDestination: true,
 *                     supportedCurrencies: [Mercoa.CurrencyCode.Usd],
 *                     metadata: {},
 *                     frozen: false,
 *                     createdAt: "2021-01-01T00:00:00Z",
 *                     updatedAt: "2021-01-01T00:00:00Z"
 *                 }],
 *             counterpartyType: [Mercoa.CounterpartyNetworkType.Entity]
 *         },
 *         paymentDestination: {
 *             type: "bankAccount",
 *             id: "pm_4794d597-70dc-4fec-b6ec-c5988e759769",
 *             accountName: "My Checking Account",
 *             bankName: "Chase",
 *             routingNumber: "12345678",
 *             accountNumber: "99988767623",
 *             accountType: Mercoa.BankType.Checking,
 *             status: Mercoa.BankStatus.Verified,
 *             isDefaultSource: true,
 *             isDefaultDestination: true,
 *             supportedCurrencies: [Mercoa.CurrencyCode.Usd],
 *             metadata: {},
 *             frozen: false,
 *             createdAt: "2021-01-01T00:00:00Z",
 *             updatedAt: "2021-01-01T00:00:00Z"
 *         },
 *         paymentDestinationId: "pm_65523ab0-043d-4706-b2b2-0b73fed92269",
 *         createdAt: "2024-01-01T00:00:00Z",
 *         updatedAt: "2024-01-01T00:00:00Z"
 *     }
 *
 * @example
 *     {
 *         type: "bankAccountToBankAccount",
 *         id: "trx_bb08e72f-19f8-45f3-bcf9-46fdc46cb2f4",
 *         status: Mercoa.TransactionStatus.Completed,
 *         amount: 10000,
 *         currency: "USD",
 *         payerId: "ent_bb08e72f-19f8-45f3-bcf9-46fdc46cb2f4",
 *         payer: {
 *             id: "ent_8545a84e-a45f-41bf-bdf1-33b42a55812c",
 *             foreignId: "MY-DB-ID-12345",
 *             name: "Acme Inc.",
 *             email: "customer@acme.com",
 *             acceptedTos: true,
 *             status: Mercoa.EntityStatus.Verified,
 *             isCustomer: true,
 *             isPayor: true,
 *             isPayee: false,
 *             isNetworkPayor: false,
 *             isNetworkPayee: false,
 *             accountType: Mercoa.AccountType.Business,
 *             updatedAt: "2024-01-02T00:00:00Z",
 *             createdAt: "2024-01-01T00:00:00Z",
 *             profile: {
 *                 business: {
 *                     email: "customer@acme.com",
 *                     legalBusinessName: "Acme Inc.",
 *                     businessType: Mercoa.BusinessType.Llc,
 *                     phone: {
 *                         countryCode: "1",
 *                         number: "4155551234"
 *                     },
 *                     address: {
 *                         addressLine1: "123 Main St",
 *                         addressLine2: "Unit 1",
 *                         city: "San Francisco",
 *                         stateOrProvince: "CA",
 *                         postalCode: "94105",
 *                         country: "US"
 *                     },
 *                     taxIdProvided: true,
 *                     taxId: {
 *                         ein: {
 *                             number: "12-3456789"
 *                         }
 *                     },
 *                     ownersProvided: true
 *                 }
 *             },
 *             accounts: [{
 *                     accountId: "85866843",
 *                     postalCode: "94105",
 *                     nameOnAccount: "John Doe"
 *                 }],
 *             paymentMethods: [{
 *                     type: "bankAccount",
 *                     id: "pm_4794d597-70dc-4fec-b6ec-c5988e759769",
 *                     accountName: "My Checking Account",
 *                     bankName: "Chase",
 *                     routingNumber: "12345678",
 *                     accountNumber: "99988767623",
 *                     accountType: Mercoa.BankType.Checking,
 *                     status: Mercoa.BankStatus.Verified,
 *                     isDefaultSource: true,
 *                     isDefaultDestination: true,
 *                     supportedCurrencies: [Mercoa.CurrencyCode.Usd],
 *                     metadata: {},
 *                     frozen: false,
 *                     createdAt: "2021-01-01T00:00:00Z",
 *                     updatedAt: "2021-01-01T00:00:00Z"
 *                 }],
 *             counterpartyType: [Mercoa.CounterpartyNetworkType.Entity]
 *         },
 *         paymentSource: {
 *             type: "bankAccount",
 *             id: "pm_4794d597-70dc-4fec-b6ec-c5988e759769",
 *             accountName: "My Checking Account",
 *             bankName: "Chase",
 *             routingNumber: "12345678",
 *             accountNumber: "99988767623",
 *             accountType: Mercoa.BankType.Checking,
 *             status: Mercoa.BankStatus.Verified,
 *             isDefaultSource: true,
 *             isDefaultDestination: true,
 *             supportedCurrencies: [Mercoa.CurrencyCode.Usd],
 *             metadata: {},
 *             frozen: false,
 *             createdAt: "2021-01-01T00:00:00Z",
 *             updatedAt: "2021-01-01T00:00:00Z"
 *         },
 *         paymentSourceId: "pm_65523ab0-043d-4706-b2b2-0b73fed92269",
 *         vendorId: "ent_bb08e72f-19f8-45f3-bcf9-46fdc46cb2f4",
 *         vendor: {
 *             id: "ent_21661ac1-a2a8-4465-a6c0-64474ba8181d",
 *             foreignId: "MY-DB-ID-90909",
 *             name: "Big Box Store",
 *             email: "vendor@bigboxstore.com",
 *             acceptedTos: false,
 *             status: Mercoa.EntityStatus.Unverified,
 *             isCustomer: false,
 *             isPayor: false,
 *             isPayee: true,
 *             isNetworkPayor: false,
 *             isNetworkPayee: false,
 *             accountType: Mercoa.AccountType.Business,
 *             updatedAt: "2024-01-02T00:00:00Z",
 *             createdAt: "2024-01-01T00:00:00Z",
 *             profile: {
 *                 business: {
 *                     email: "vendor@bigboxstore.com",
 *                     legalBusinessName: "Big Box Store",
 *                     businessType: Mercoa.BusinessType.PublicCorporation,
 *                     taxIdProvided: false,
 *                     ownersProvided: false
 *                 }
 *             },
 *             paymentMethods: [{
 *                     type: "bankAccount",
 *                     id: "pm_7610541f-4619-4033-8620-cfccfb811293",
 *                     accountName: "Vendor Checking Account",
 *                     bankName: "Chase",
 *                     routingNumber: "66554433",
 *                     accountNumber: "55934059697648",
 *                     accountType: Mercoa.BankType.Checking,
 *                     status: Mercoa.BankStatus.New,
 *                     isDefaultSource: true,
 *                     isDefaultDestination: true,
 *                     supportedCurrencies: [Mercoa.CurrencyCode.Usd],
 *                     metadata: {},
 *                     frozen: false,
 *                     createdAt: "2021-01-01T00:00:00Z",
 *                     updatedAt: "2021-01-01T00:00:00Z"
 *                 }],
 *             counterpartyType: [Mercoa.CounterpartyNetworkType.Entity]
 *         },
 *         paymentDestination: {
 *             type: "bankAccount",
 *             id: "pm_4794d597-70dc-4fec-b6ec-c5988e759769",
 *             accountName: "My Checking Account",
 *             bankName: "Chase",
 *             routingNumber: "12345678",
 *             accountNumber: "99988767623",
 *             accountType: Mercoa.BankType.Checking,
 *             status: Mercoa.BankStatus.Verified,
 *             isDefaultSource: true,
 *             isDefaultDestination: true,
 *             supportedCurrencies: [Mercoa.CurrencyCode.Usd],
 *             metadata: {},
 *             frozen: false,
 *             createdAt: "2021-01-01T00:00:00Z",
 *             updatedAt: "2021-01-01T00:00:00Z"
 *         },
 *         paymentDestinationId: "pm_65523ab0-043d-4706-b2b2-0b73fed92269",
 *         createdAt: "2024-01-01T00:00:00Z",
 *         updatedAt: "2024-01-01T00:00:00Z"
 *     }
 *
 * @example
 *     {
 *         type: "bankAccountToBankAccount",
 *         id: "trx_bb08e72f-19f8-45f3-bcf9-46fdc46cb2f4",
 *         status: Mercoa.TransactionStatus.Failed,
 *         amount: 10000,
 *         currency: "USD",
 *         payerId: "ent_bb08e72f-19f8-45f3-bcf9-46fdc46cb2f4",
 *         payer: {
 *             id: "ent_8545a84e-a45f-41bf-bdf1-33b42a55812c",
 *             foreignId: "MY-DB-ID-12345",
 *             name: "Acme Inc.",
 *             email: "customer@acme.com",
 *             acceptedTos: true,
 *             status: Mercoa.EntityStatus.Verified,
 *             isCustomer: true,
 *             isPayor: true,
 *             isPayee: false,
 *             isNetworkPayor: false,
 *             isNetworkPayee: false,
 *             accountType: Mercoa.AccountType.Business,
 *             updatedAt: "2024-01-02T00:00:00Z",
 *             createdAt: "2024-01-01T00:00:00Z",
 *             profile: {
 *                 business: {
 *                     email: "customer@acme.com",
 *                     legalBusinessName: "Acme Inc.",
 *                     businessType: Mercoa.BusinessType.Llc,
 *                     phone: {
 *                         countryCode: "1",
 *                         number: "4155551234"
 *                     },
 *                     address: {
 *                         addressLine1: "123 Main St",
 *                         addressLine2: "Unit 1",
 *                         city: "San Francisco",
 *                         stateOrProvince: "CA",
 *                         postalCode: "94105",
 *                         country: "US"
 *                     },
 *                     taxIdProvided: true,
 *                     taxId: {
 *                         ein: {
 *                             number: "12-3456789"
 *                         }
 *                     },
 *                     ownersProvided: true
 *                 }
 *             },
 *             accounts: [{
 *                     accountId: "85866843",
 *                     postalCode: "94105",
 *                     nameOnAccount: "John Doe"
 *                 }],
 *             paymentMethods: [{
 *                     type: "bankAccount",
 *                     id: "pm_4794d597-70dc-4fec-b6ec-c5988e759769",
 *                     accountName: "My Checking Account",
 *                     bankName: "Chase",
 *                     routingNumber: "12345678",
 *                     accountNumber: "99988767623",
 *                     accountType: Mercoa.BankType.Checking,
 *                     status: Mercoa.BankStatus.Verified,
 *                     isDefaultSource: true,
 *                     isDefaultDestination: true,
 *                     supportedCurrencies: [Mercoa.CurrencyCode.Usd],
 *                     metadata: {},
 *                     frozen: false,
 *                     createdAt: "2021-01-01T00:00:00Z",
 *                     updatedAt: "2021-01-01T00:00:00Z"
 *                 }],
 *             counterpartyType: [Mercoa.CounterpartyNetworkType.Entity]
 *         },
 *         paymentSource: {
 *             type: "bankAccount",
 *             id: "pm_4794d597-70dc-4fec-b6ec-c5988e759769",
 *             accountName: "My Checking Account",
 *             bankName: "Chase",
 *             routingNumber: "12345678",
 *             accountNumber: "99988767623",
 *             accountType: Mercoa.BankType.Checking,
 *             status: Mercoa.BankStatus.Verified,
 *             isDefaultSource: true,
 *             isDefaultDestination: true,
 *             supportedCurrencies: [Mercoa.CurrencyCode.Usd],
 *             metadata: {},
 *             frozen: false,
 *             createdAt: "2021-01-01T00:00:00Z",
 *             updatedAt: "2021-01-01T00:00:00Z"
 *         },
 *         paymentSourceId: "pm_65523ab0-043d-4706-b2b2-0b73fed92269",
 *         vendorId: "ent_bb08e72f-19f8-45f3-bcf9-46fdc46cb2f4",
 *         vendor: {
 *             id: "ent_21661ac1-a2a8-4465-a6c0-64474ba8181d",
 *             foreignId: "MY-DB-ID-90909",
 *             name: "Big Box Store",
 *             email: "vendor@bigboxstore.com",
 *             acceptedTos: false,
 *             status: Mercoa.EntityStatus.Unverified,
 *             isCustomer: false,
 *             isPayor: false,
 *             isPayee: true,
 *             isNetworkPayor: false,
 *             isNetworkPayee: false,
 *             accountType: Mercoa.AccountType.Business,
 *             updatedAt: "2024-01-02T00:00:00Z",
 *             createdAt: "2024-01-01T00:00:00Z",
 *             profile: {
 *                 business: {
 *                     email: "vendor@bigboxstore.com",
 *                     legalBusinessName: "Big Box Store",
 *                     businessType: Mercoa.BusinessType.PublicCorporation,
 *                     taxIdProvided: false,
 *                     ownersProvided: false
 *                 }
 *             },
 *             paymentMethods: [{
 *                     type: "bankAccount",
 *                     id: "pm_7610541f-4619-4033-8620-cfccfb811293",
 *                     accountName: "Vendor Checking Account",
 *                     bankName: "Chase",
 *                     routingNumber: "66554433",
 *                     accountNumber: "55934059697648",
 *                     accountType: Mercoa.BankType.Checking,
 *                     status: Mercoa.BankStatus.New,
 *                     isDefaultSource: true,
 *                     isDefaultDestination: true,
 *                     supportedCurrencies: [Mercoa.CurrencyCode.Usd],
 *                     metadata: {},
 *                     frozen: false,
 *                     createdAt: "2021-01-01T00:00:00Z",
 *                     updatedAt: "2021-01-01T00:00:00Z"
 *                 }],
 *             counterpartyType: [Mercoa.CounterpartyNetworkType.Entity]
 *         },
 *         paymentDestination: {
 *             type: "bankAccount",
 *             id: "pm_4794d597-70dc-4fec-b6ec-c5988e759769",
 *             accountName: "My Checking Account",
 *             bankName: "Chase",
 *             routingNumber: "12345678",
 *             accountNumber: "99988767623",
 *             accountType: Mercoa.BankType.Checking,
 *             status: Mercoa.BankStatus.Verified,
 *             isDefaultSource: true,
 *             isDefaultDestination: true,
 *             supportedCurrencies: [Mercoa.CurrencyCode.Usd],
 *             metadata: {},
 *             frozen: false,
 *             createdAt: "2021-01-01T00:00:00Z",
 *             updatedAt: "2021-01-01T00:00:00Z"
 *         },
 *         paymentDestinationId: "pm_65523ab0-043d-4706-b2b2-0b73fed92269",
 *         createdAt: "2024-01-01T00:00:00Z",
 *         updatedAt: "2024-01-01T00:00:00Z"
 *     }
 *
 * @example
 *     {
 *         type: "bankAccountToBankAccount",
 *         id: "trx_bb08e72f-19f8-45f3-bcf9-46fdc46cb2f4",
 *         status: Mercoa.TransactionStatus.Returned,
 *         amount: 10000,
 *         currency: "USD",
 *         payerId: "ent_bb08e72f-19f8-45f3-bcf9-46fdc46cb2f4",
 *         payer: {
 *             id: "ent_8545a84e-a45f-41bf-bdf1-33b42a55812c",
 *             foreignId: "MY-DB-ID-12345",
 *             name: "Acme Inc.",
 *             email: "customer@acme.com",
 *             acceptedTos: true,
 *             status: Mercoa.EntityStatus.Verified,
 *             isCustomer: true,
 *             isPayor: true,
 *             isPayee: false,
 *             isNetworkPayor: false,
 *             isNetworkPayee: false,
 *             accountType: Mercoa.AccountType.Business,
 *             updatedAt: "2024-01-02T00:00:00Z",
 *             createdAt: "2024-01-01T00:00:00Z",
 *             profile: {
 *                 business: {
 *                     email: "customer@acme.com",
 *                     legalBusinessName: "Acme Inc.",
 *                     businessType: Mercoa.BusinessType.Llc,
 *                     phone: {
 *                         countryCode: "1",
 *                         number: "4155551234"
 *                     },
 *                     address: {
 *                         addressLine1: "123 Main St",
 *                         addressLine2: "Unit 1",
 *                         city: "San Francisco",
 *                         stateOrProvince: "CA",
 *                         postalCode: "94105",
 *                         country: "US"
 *                     },
 *                     taxIdProvided: true,
 *                     taxId: {
 *                         ein: {
 *                             number: "12-3456789"
 *                         }
 *                     },
 *                     ownersProvided: true
 *                 }
 *             },
 *             accounts: [{
 *                     accountId: "85866843",
 *                     postalCode: "94105",
 *                     nameOnAccount: "John Doe"
 *                 }],
 *             paymentMethods: [{
 *                     type: "bankAccount",
 *                     id: "pm_4794d597-70dc-4fec-b6ec-c5988e759769",
 *                     accountName: "My Checking Account",
 *                     bankName: "Chase",
 *                     routingNumber: "12345678",
 *                     accountNumber: "99988767623",
 *                     accountType: Mercoa.BankType.Checking,
 *                     status: Mercoa.BankStatus.Verified,
 *                     isDefaultSource: true,
 *                     isDefaultDestination: true,
 *                     supportedCurrencies: [Mercoa.CurrencyCode.Usd],
 *                     metadata: {},
 *                     frozen: false,
 *                     createdAt: "2021-01-01T00:00:00Z",
 *                     updatedAt: "2021-01-01T00:00:00Z"
 *                 }],
 *             counterpartyType: [Mercoa.CounterpartyNetworkType.Entity]
 *         },
 *         paymentSource: {
 *             type: "bankAccount",
 *             id: "pm_4794d597-70dc-4fec-b6ec-c5988e759769",
 *             accountName: "My Checking Account",
 *             bankName: "Chase",
 *             routingNumber: "12345678",
 *             accountNumber: "99988767623",
 *             accountType: Mercoa.BankType.Checking,
 *             status: Mercoa.BankStatus.Verified,
 *             isDefaultSource: true,
 *             isDefaultDestination: true,
 *             supportedCurrencies: [Mercoa.CurrencyCode.Usd],
 *             metadata: {},
 *             frozen: false,
 *             createdAt: "2021-01-01T00:00:00Z",
 *             updatedAt: "2021-01-01T00:00:00Z"
 *         },
 *         paymentSourceId: "pm_65523ab0-043d-4706-b2b2-0b73fed92269",
 *         vendorId: "ent_bb08e72f-19f8-45f3-bcf9-46fdc46cb2f4",
 *         vendor: {
 *             id: "ent_21661ac1-a2a8-4465-a6c0-64474ba8181d",
 *             foreignId: "MY-DB-ID-90909",
 *             name: "Big Box Store",
 *             email: "vendor@bigboxstore.com",
 *             acceptedTos: false,
 *             status: Mercoa.EntityStatus.Unverified,
 *             isCustomer: false,
 *             isPayor: false,
 *             isPayee: true,
 *             isNetworkPayor: false,
 *             isNetworkPayee: false,
 *             accountType: Mercoa.AccountType.Business,
 *             updatedAt: "2024-01-02T00:00:00Z",
 *             createdAt: "2024-01-01T00:00:00Z",
 *             profile: {
 *                 business: {
 *                     email: "vendor@bigboxstore.com",
 *                     legalBusinessName: "Big Box Store",
 *                     businessType: Mercoa.BusinessType.PublicCorporation,
 *                     taxIdProvided: false,
 *                     ownersProvided: false
 *                 }
 *             },
 *             paymentMethods: [{
 *                     type: "bankAccount",
 *                     id: "pm_7610541f-4619-4033-8620-cfccfb811293",
 *                     accountName: "Vendor Checking Account",
 *                     bankName: "Chase",
 *                     routingNumber: "66554433",
 *                     accountNumber: "55934059697648",
 *                     accountType: Mercoa.BankType.Checking,
 *                     status: Mercoa.BankStatus.New,
 *                     isDefaultSource: true,
 *                     isDefaultDestination: true,
 *                     supportedCurrencies: [Mercoa.CurrencyCode.Usd],
 *                     metadata: {},
 *                     frozen: false,
 *                     createdAt: "2021-01-01T00:00:00Z",
 *                     updatedAt: "2021-01-01T00:00:00Z"
 *                 }],
 *             counterpartyType: [Mercoa.CounterpartyNetworkType.Entity]
 *         },
 *         paymentDestination: {
 *             type: "bankAccount",
 *             id: "pm_4794d597-70dc-4fec-b6ec-c5988e759769",
 *             accountName: "My Checking Account",
 *             bankName: "Chase",
 *             routingNumber: "12345678",
 *             accountNumber: "99988767623",
 *             accountType: Mercoa.BankType.Checking,
 *             status: Mercoa.BankStatus.Verified,
 *             isDefaultSource: true,
 *             isDefaultDestination: true,
 *             supportedCurrencies: [Mercoa.CurrencyCode.Usd],
 *             metadata: {},
 *             frozen: false,
 *             createdAt: "2021-01-01T00:00:00Z",
 *             updatedAt: "2021-01-01T00:00:00Z"
 *         },
 *         paymentDestinationId: "pm_65523ab0-043d-4706-b2b2-0b73fed92269",
 *         createdAt: "2024-01-01T00:00:00Z",
 *         updatedAt: "2024-01-01T00:00:00Z"
 *     }
 *
 * @example
 *     {
 *         type: "bankAccountToMailedCheck",
 *         id: "trx_bb08e72f-19f8-45f3-bcf9-46fdc46cb2f4",
 *         checkNumber: 4005,
 *         status: Mercoa.TransactionStatus.Completed,
 *         amount: 10000,
 *         currency: "USD",
 *         payerId: "ent_bb08e72f-19f8-45f3-bcf9-46fdc46cb2f4",
 *         payer: {
 *             id: "ent_8545a84e-a45f-41bf-bdf1-33b42a55812c",
 *             foreignId: "MY-DB-ID-12345",
 *             name: "Acme Inc.",
 *             email: "customer@acme.com",
 *             acceptedTos: true,
 *             status: Mercoa.EntityStatus.Verified,
 *             isCustomer: true,
 *             isPayor: true,
 *             isPayee: false,
 *             isNetworkPayor: false,
 *             isNetworkPayee: false,
 *             accountType: Mercoa.AccountType.Business,
 *             updatedAt: "2024-01-02T00:00:00Z",
 *             createdAt: "2024-01-01T00:00:00Z",
 *             profile: {
 *                 business: {
 *                     email: "customer@acme.com",
 *                     legalBusinessName: "Acme Inc.",
 *                     businessType: Mercoa.BusinessType.Llc,
 *                     phone: {
 *                         countryCode: "1",
 *                         number: "4155551234"
 *                     },
 *                     address: {
 *                         addressLine1: "123 Main St",
 *                         addressLine2: "Unit 1",
 *                         city: "San Francisco",
 *                         stateOrProvince: "CA",
 *                         postalCode: "94105",
 *                         country: "US"
 *                     },
 *                     taxIdProvided: true,
 *                     taxId: {
 *                         ein: {
 *                             number: "12-3456789"
 *                         }
 *                     },
 *                     ownersProvided: true
 *                 }
 *             },
 *             accounts: [{
 *                     accountId: "85866843",
 *                     postalCode: "94105",
 *                     nameOnAccount: "John Doe"
 *                 }],
 *             paymentMethods: [{
 *                     type: "bankAccount",
 *                     id: "pm_4794d597-70dc-4fec-b6ec-c5988e759769",
 *                     accountName: "My Checking Account",
 *                     bankName: "Chase",
 *                     routingNumber: "12345678",
 *                     accountNumber: "99988767623",
 *                     accountType: Mercoa.BankType.Checking,
 *                     status: Mercoa.BankStatus.Verified,
 *                     isDefaultSource: true,
 *                     isDefaultDestination: true,
 *                     supportedCurrencies: [Mercoa.CurrencyCode.Usd],
 *                     metadata: {},
 *                     frozen: false,
 *                     createdAt: "2021-01-01T00:00:00Z",
 *                     updatedAt: "2021-01-01T00:00:00Z"
 *                 }],
 *             counterpartyType: [Mercoa.CounterpartyNetworkType.Entity]
 *         },
 *         paymentSource: {
 *             type: "bankAccount",
 *             id: "pm_4794d597-70dc-4fec-b6ec-c5988e759769",
 *             accountName: "My Checking Account",
 *             bankName: "Chase",
 *             routingNumber: "12345678",
 *             accountNumber: "99988767623",
 *             accountType: Mercoa.BankType.Checking,
 *             status: Mercoa.BankStatus.Verified,
 *             isDefaultSource: true,
 *             isDefaultDestination: true,
 *             supportedCurrencies: [Mercoa.CurrencyCode.Usd],
 *             metadata: {},
 *             frozen: false,
 *             createdAt: "2021-01-01T00:00:00Z",
 *             updatedAt: "2021-01-01T00:00:00Z"
 *         },
 *         paymentSourceId: "pm_65523ab0-043d-4706-b2b2-0b73fed92269",
 *         vendorId: "ent_bb08e72f-19f8-45f3-bcf9-46fdc46cb2f4",
 *         vendor: {
 *             id: "ent_21661ac1-a2a8-4465-a6c0-64474ba8181d",
 *             foreignId: "MY-DB-ID-90909",
 *             name: "Big Box Store",
 *             email: "vendor@bigboxstore.com",
 *             acceptedTos: false,
 *             status: Mercoa.EntityStatus.Unverified,
 *             isCustomer: false,
 *             isPayor: false,
 *             isPayee: true,
 *             isNetworkPayor: false,
 *             isNetworkPayee: false,
 *             accountType: Mercoa.AccountType.Business,
 *             updatedAt: "2024-01-02T00:00:00Z",
 *             createdAt: "2024-01-01T00:00:00Z",
 *             profile: {
 *                 business: {
 *                     email: "vendor@bigboxstore.com",
 *                     legalBusinessName: "Big Box Store",
 *                     businessType: Mercoa.BusinessType.PublicCorporation,
 *                     taxIdProvided: false,
 *                     ownersProvided: false
 *                 }
 *             },
 *             paymentMethods: [{
 *                     type: "bankAccount",
 *                     id: "pm_7610541f-4619-4033-8620-cfccfb811293",
 *                     accountName: "Vendor Checking Account",
 *                     bankName: "Chase",
 *                     routingNumber: "66554433",
 *                     accountNumber: "55934059697648",
 *                     accountType: Mercoa.BankType.Checking,
 *                     status: Mercoa.BankStatus.New,
 *                     isDefaultSource: true,
 *                     isDefaultDestination: true,
 *                     supportedCurrencies: [Mercoa.CurrencyCode.Usd],
 *                     metadata: {},
 *                     frozen: false,
 *                     createdAt: "2021-01-01T00:00:00Z",
 *                     updatedAt: "2021-01-01T00:00:00Z"
 *                 }],
 *             counterpartyType: [Mercoa.CounterpartyNetworkType.Entity]
 *         },
 *         paymentDestination: {
 *             type: "check",
 *             id: "pm_5fde2f4a-facc-48ef-8f0d-6b7d087c7b18",
 *             payToTheOrderOf: "John Doe",
 *             addressLine1: "123 Main St",
 *             addressLine2: "Apt 1",
 *             city: "New York",
 *             stateOrProvince: "NY",
 *             postalCode: "10001",
 *             country: "US",
 *             isDefaultSource: false,
 *             isDefaultDestination: true,
 *             supportedCurrencies: [Mercoa.CurrencyCode.Usd],
 *             metadata: {},
 *             frozen: false,
 *             createdAt: "2021-01-01T00:00:00Z",
 *             updatedAt: "2021-01-01T00:00:00Z"
 *         },
 *         paymentDestinationId: "pm_68ff13bf-390d-49d3-a29a-3fe239f12b92",
 *         createdAt: "2024-01-01T00:00:00Z",
 *         updatedAt: "2024-01-01T00:00:00Z"
 *     }
 */
export type TransactionResponseWithoutInvoices =
    | Mercoa.TransactionResponseWithoutInvoices.BankAccountToBankAccount
    | Mercoa.TransactionResponseWithoutInvoices.BankAccountToMailedCheck
    | Mercoa.TransactionResponseWithoutInvoices.BankAccountToWallet
    | Mercoa.TransactionResponseWithoutInvoices.CardToWallet
    | Mercoa.TransactionResponseWithoutInvoices.WalletToBankAccount
    | Mercoa.TransactionResponseWithoutInvoices.Custom
    | Mercoa.TransactionResponseWithoutInvoices.OffPlatform;

export declare namespace TransactionResponseWithoutInvoices {
    interface BankAccountToBankAccount extends Mercoa.TransactionResponseAchBase {
        type: "bankAccountToBankAccount";
    }

    interface BankAccountToMailedCheck extends Mercoa.TransactionResponseMailedCheckBase {
        type: "bankAccountToMailedCheck";
    }

    interface BankAccountToWallet extends Mercoa.TransactionResponseAchBase {
        type: "bankAccountToWallet";
    }

    interface CardToWallet extends Mercoa.TransactionResponseBase {
        type: "cardToWallet";
    }

    interface WalletToBankAccount extends Mercoa.TransactionResponseAchBase {
        type: "walletToBankAccount";
    }

    interface Custom extends Mercoa.TransactionResponseBase {
        type: "custom";
    }

    interface OffPlatform extends Mercoa.TransactionResponseBase {
        type: "offPlatform";
    }
}
