/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors/index.js";
import * as core from "../../../../core/index.js";

export class Unimplemented extends errors.MercoaError {
    constructor(body: string, rawResponse?: core.RawResponse) {
        super({
            message: "Unimplemented",
            statusCode: 501,
            body: body,
            rawResponse: rawResponse,
        });
        Object.setPrototypeOf(this, Unimplemented.prototype);
    }
}
