/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Mercoa from "../../../../api/index";
import * as core from "../../../../core";
import { BankType } from "./BankType";
import { BankStatus } from "./BankStatus";
import { BankAccountCheckOptions } from "./BankAccountCheckOptions";
import { PaymentMethodBaseResponse } from "./PaymentMethodBaseResponse";

export const BankAccountResponse: core.serialization.ObjectSchema<
    serializers.BankAccountResponse.Raw,
    Mercoa.BankAccountResponse
> = core.serialization
    .object({
        accountName: core.serialization.string(),
        bankName: core.serialization.string(),
        routingNumber: core.serialization.string(),
        accountNumber: core.serialization.string(),
        accountType: BankType,
        status: BankStatus,
        checkOptions: BankAccountCheckOptions.optional(),
    })
    .extend(PaymentMethodBaseResponse);

export declare namespace BankAccountResponse {
    export interface Raw extends PaymentMethodBaseResponse.Raw {
        accountName: string;
        bankName: string;
        routingNumber: string;
        accountNumber: string;
        accountType: BankType.Raw;
        status: BankStatus.Raw;
        checkOptions?: BankAccountCheckOptions.Raw | null;
    }
}
