/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Mercoa from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { WalletBalance } from "./WalletBalance.js";
import { PaymentMethodBaseResponse } from "./PaymentMethodBaseResponse.js";

export const WalletResponse: core.serialization.ObjectSchema<serializers.WalletResponse.Raw, Mercoa.WalletResponse> =
    core.serialization
        .object({
            availableBalance: WalletBalance,
            pendingBalance: WalletBalance,
        })
        .extend(PaymentMethodBaseResponse);

export declare namespace WalletResponse {
    export interface Raw extends PaymentMethodBaseResponse.Raw {
        availableBalance: WalletBalance.Raw;
        pendingBalance: WalletBalance.Raw;
    }
}
