/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Mercoa from "../../../../api";
import * as core from "../../../../core";

export const BankType: core.serialization.Schema<serializers.BankType.Raw, Mercoa.BankType> = core.serialization.enum_([
    "CHECKING",
    "SAVINGS",
    "UNKNOWN",
]);

export declare namespace BankType {
    type Raw = "CHECKING" | "SAVINGS" | "UNKNOWN";
}
