/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Mercoa from "../../../index";

export interface BankAccountPaymentDestinationOptions {
    /** Delivery method for ACH payments. Defaults to ACH_SAME_DAY. */
    delivery?: Mercoa.BankDeliveryMethod;
}
