/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Mercoa from "../../../index.js";

/**
 * @example
 *     {
 *         number: 0,
 *         dueDate: "2025-06-18",
 *         amount: 12000,
 *         type: Mercoa.BnplInstallmentType.DownPayment
 *     }
 *
 * @example
 *     {
 *         number: 1,
 *         dueDate: "2025-07-02",
 *         amount: 27422,
 *         type: Mercoa.BnplInstallmentType.Regular
 *     }
 */
export interface BnplInstallment {
    number: number;
    dueDate: string;
    amount: number;
    type: Mercoa.BnplInstallmentType;
}
