/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Mercoa from "../../../index";

/**
 * @example
 *     {
 *         invoices: [{
 *                 invoiceId: "in_26e7b5d3-a739-4b23-9ad9-6aaa085f47a9",
 *                 text: "This is a reason for my action",
 *                 userId: "user_e24fc81c-c5ee-47e8-af42-4fe29d895506"
 *             }]
 *     }
 */
export interface BulkInvoiceApprovalRequest {
    invoices: Mercoa.ApprovalRequestWithId[];
}
