/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CheckDeliveryMethod = "PRINT" | "MAIL" | "MAIL_PRIORITY" | "MAIL_UPS_NEXT_DAY";
export const CheckDeliveryMethod = {
    Print: "PRINT",
    Mail: "MAIL",
    MailPriority: "MAIL_PRIORITY",
    MailUpsNextDay: "MAIL_UPS_NEXT_DAY",
} as const;
