/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Mercoa from "../../../index";

/**
 * @example
 *     {
 *         status: Mercoa.InvoiceStatus.Draft,
 *         amount: 100,
 *         currency: Mercoa.CurrencyCode.Usd,
 *         invoiceDate: new Date("2021-01-01T00:00:00.000Z"),
 *         dueDate: new Date("2021-01-31T00:00:00.000Z"),
 *         invoiceNumber: "INV-123",
 *         noteToSelf: "For the month of January",
 *         serviceStartDate: new Date("2021-01-01T00:00:00.000Z"),
 *         serviceEndDate: new Date("2021-01-31T00:00:00.000Z"),
 *         payerId: "ent_8545a84e-a45f-41bf-bdf1-33b42a55812c",
 *         paymentSourceId: "pm_4794d597-70dc-4fec-b6ec-c5988e759769",
 *         vendorId: "ent_21661ac1-a2a8-4465-a6c0-64474ba8181d",
 *         paymentDestinationId: "pm_5fde2f4a-facc-48ef-8f0d-6b7d087c7b18",
 *         paymentDestinationOptions: {
 *             type: "check",
 *             delivery: Mercoa.CheckDeliveryMethod.Mail
 *         },
 *         lineItems: [{
 *                 amount: 100,
 *                 currency: Mercoa.CurrencyCode.Usd,
 *                 description: "Product A",
 *                 name: "Product A",
 *                 quantity: 1,
 *                 unitPrice: 100,
 *                 serviceStartDate: new Date("2021-01-01T00:00:00.000Z"),
 *                 serviceEndDate: new Date("2021-01-31T00:00:00.000Z"),
 *                 metadata: {
 *                     "key1": "value1",
 *                     "key2": "value2"
 *                 },
 *                 glAccountId: "600394"
 *             }],
 *         creatorEntityId: "ent_8545a84e-a45f-41bf-bdf1-33b42a55812c",
 *         creatorUserId: "user_e24fc81c-c5ee-47e8-af42-4fe29d895506"
 *     }
 */
export interface InvoiceRequest {
    status?: Mercoa.InvoiceStatus;
    /** Total amount of invoice in major units. If the entered amount has more decimal places than the currency supports, trailing decimals will be truncated. */
    amount?: number;
    /** Currency code for the amount. Defaults to USD. */
    currency?: Mercoa.CurrencyCode;
    /** Date the invoice was issued. */
    invoiceDate?: Date;
    /** Date when funds will be deducted from payer's account. */
    deductionDate?: Date;
    /** Date of funds settlement. */
    settlementDate?: Date;
    /** Due date of invoice. */
    dueDate?: Date;
    invoiceNumber?: string;
    /** Note to self or memo on invoice. */
    noteToSelf?: string;
    serviceStartDate?: Date;
    serviceEndDate?: Date;
    payerId?: Mercoa.EntityId;
    /** ID of payment source for this invoice. If not provided, will attempt to use the default payment source for the payer when creating an invoice if a default payment source exists for the payer. */
    paymentSourceId?: Mercoa.PaymentMethodId;
    vendorId?: Mercoa.EntityId;
    /** ID of payment destination for this invoice. If not provided, will attempt to use the default payment destination for the vendor when creating an invoice if a default payment destination exists for the vendor. */
    paymentDestinationId?: Mercoa.PaymentMethodId;
    /** Options for the payment destination. Depending on the payment destination, this may include things such as check delivery method. */
    paymentDestinationOptions?: Mercoa.PaymentDestinationOptions;
    /** Set approvers for this invoice. */
    approvers?: Mercoa.ApprovalSlotAssignment[];
    lineItems?: Mercoa.InvoiceLineItemRequest[];
    /** Metadata associated with this invoice. You can specify up to 10 keys, with key names up to 40 characters long and values up to 200 characters long. */
    metadata?: Record<string, string>;
    /** The ID used to identify this invoice in your system. This ID must be unique within each creatorEntity in your system, e.g. two invoices with the same creatorEntity may not have the same foreign ID. */
    foreignId?: string;
    /** Base64 encoded image or PDF of invoice document. PNG, JPG, and PDF are supported. 10MB max. If the invoice already has a document, this will add a new document to the invoice. */
    document?: string;
    /** DEPRECATED. Use document field instead. */
    uploadedImage?: string;
    /** ID of entity who created this invoice. If creating a payable invoice (AP), this must be the same as the payerId. If creating a receivable invoice (AR), this must be the same as the vendorId. */
    creatorEntityId?: Mercoa.EntityId;
    /** ID of entity user who created this invoice. */
    creatorUserId?: Mercoa.EntityUserId;
}
