/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PaymentMonthRepeatType = "start" | "end";

export const PaymentMonthRepeatType = {
    Start: "start",
    End: "end",
} as const;
