/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Mercoa } from "@mercoa/javascript";

export interface RepresentativeRequest {
    name: Mercoa.FullName;
    phone: Mercoa.PhoneNumber;
    email: string;
    address: Mercoa.Address;
    birthDate: Mercoa.BirthDate;
    governmentId: Mercoa.IndividualGovernmentId;
    responsibilities: Mercoa.Responsibilities;
}
