/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Mercoa from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { ActionBase } from "./ActionBase.js";

export const EmailCollectionActionResponse: core.serialization.ObjectSchema<
    serializers.EmailCollectionActionResponse.Raw,
    Mercoa.EmailCollectionActionResponse
> = core.serialization
    .object({
        subject: core.serialization.string(),
        body: core.serialization.string(),
    })
    .extend(ActionBase);

export declare namespace EmailCollectionActionResponse {
    export interface Raw extends ActionBase.Raw {
        subject: string;
        body: string;
    }
}
