/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../../index";
import * as Mercoa from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";
import { UserNotificationPolicyResponse } from "../../../../../../entityTypes/types/UserNotificationPolicyResponse";

export const Response: core.serialization.Schema<
    serializers.entity.user.notificationPolicy.getAll.Response.Raw,
    Mercoa.UserNotificationPolicyResponse[]
> = core.serialization.list(UserNotificationPolicyResponse);

export declare namespace Response {
    export type Raw = UserNotificationPolicyResponse.Raw[];
}
