/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Mercoa from "../../../../../index";

export type ExternalAccountingSystemCompanyResponse = Mercoa.entity.ExternalAccountingSystemCompanyResponse.Codat;

export declare namespace ExternalAccountingSystemCompanyResponse {
    interface Codat extends Mercoa.entity.CodatCompanyResponse {
        type: "codat";
    }
}
