/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Mercoa from "../../../../api/index";
import * as core from "../../../../core";
import { InvoiceResponse } from "../../invoiceTypes/types/InvoiceResponse";
import { TransactionResponseAchBase } from "./TransactionResponseAchBase";

export const TransactionResponseBankToBankWithInvoices: core.serialization.ObjectSchema<
    serializers.TransactionResponseBankToBankWithInvoices.Raw,
    Mercoa.TransactionResponseBankToBankWithInvoices
> = core.serialization
    .object({
        invoices: core.serialization.list(InvoiceResponse),
    })
    .extend(TransactionResponseAchBase);

export declare namespace TransactionResponseBankToBankWithInvoices {
    interface Raw extends TransactionResponseAchBase.Raw {
        invoices: InvoiceResponse.Raw[];
    }
}
