/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ColorSchemeResponse {
    primaryColor?: string;
    secondaryColor?: string;
    logoBackgroundColor?: string;
}
