/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Mercoa from "../../../index.js";

export interface CommonOnboardingOptionsRequest {
    termsOfService?: Mercoa.OnboardingOptionRequest;
    email?: Mercoa.OnboardingOptionRequest;
    name?: Mercoa.OnboardingOptionRequest;
    address?: Mercoa.OnboardingOptionRequest;
    phone?: Mercoa.OnboardingOptionRequest;
    tenNinetyNine?: Mercoa.OnboardingOptionRequest;
    w9?: Mercoa.OnboardingOptionRequest;
    bankStatement?: Mercoa.OnboardingOptionRequest;
}
