/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Mercoa from "../../../index";

export interface EmailProviderRequest {
    sender: Mercoa.EmailSenderRequest;
    inboxDomain: string;
}
