/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Mercoa from "../../..";

export type ExternalAccountingSystemProviderRequest = Mercoa.ExternalAccountingSystemProviderRequest.Codat;

export declare namespace ExternalAccountingSystemProviderRequest {
    interface Codat extends Mercoa.CodatProviderRequest {
        type: "codat";
    }
}
