/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Mercoa from "../../../index";

/**
 * @example
 *     {
 *         trigger: [],
 *         rule: {
 *             type: "approver",
 *             numApprovers: 2,
 *             identifierList: {
 *                 type: "userList",
 *                 value: ["usr_8545a84e-a45f-41bf-bdf1-33b42a55812c", "usr_21661ac1-a2a8-4465-a6c0-64474ba8181d"]
 *             }
 *         },
 *         upstreamPolicyId: "root"
 *     }
 *
 * @example
 *     {
 *         trigger: [{
 *                 type: "amount",
 *                 amount: 100,
 *                 currency: Mercoa.CurrencyCode.Usd
 *             }],
 *         rule: {
 *             type: "approver",
 *             numApprovers: 2,
 *             identifierList: {
 *                 type: "rolesList",
 *                 value: ["Admin", "Controller"]
 *             }
 *         },
 *         upstreamPolicyId: "root"
 *     }
 *
 * @example
 *     {
 *         trigger: [{
 *                 type: "amount",
 *                 amount: 100,
 *                 currency: Mercoa.CurrencyCode.Usd
 *             }, {
 *                 type: "vendor",
 *                 vendorIds: ["ent_21661ac1-a2a8-4465-a6c0-64474ba8181d"]
 *             }, {
 *                 type: "metadata",
 *                 key: "property_id",
 *                 value: ["123456", "789012"]
 *             }, {
 *                 type: "catchall"
 *             }],
 *         rule: {
 *             type: "approver",
 *             numApprovers: 2,
 *             identifierList: {
 *                 type: "rolesList",
 *                 value: ["Admin", "Controller"]
 *             }
 *         },
 *         upstreamPolicyId: "root"
 *     }
 */
export interface ApprovalPolicyRequest {
    /** List of triggers that will cause this policy to be evaluated. If no triggers are provided, the policy will be evaluated for all invoices. */
    trigger: Mercoa.Trigger[];
    rule: Mercoa.Rule;
    /** The policy ID of the previous approval policy in the chain of policies. Use 'root' if no upstreamPolicyId is intended to be set. */
    upstreamPolicyId: Mercoa.ApprovalPolicyId;
}
