/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Mercoa from "../../..";

export interface BusinessProfileRequest {
    email?: string;
    legalBusinessName: string;
    businessType?: Mercoa.BusinessType;
    phone?: Mercoa.PhoneNumber;
    doingBusinessAs?: string;
    /** Website URL for the business. Must be in the format http://www.example.com */
    website?: string;
    /** Description of the business. Required for KYB if website is not provided. */
    description?: string;
    address?: Mercoa.Address;
    /** Tax ID for the business. Currently only EIN is supported. Must be in the format XX-XXXXXXX. */
    taxId?: Mercoa.TaxId;
    /** Date of business formation */
    formationDate?: Date;
}
