/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Mercoa from "../../../index";

/**
 * @example
 *     {
 *         disabled: false,
 *         additionalRoles: ["admin", "approver"],
 *         type: Mercoa.NotificationType.InvoiceApprovalNeeded
 *     }
 *
 * @example
 *     {
 *         disabled: false,
 *         additionalRoles: ["admin", "bookkeeper"],
 *         type: Mercoa.NotificationType.InvoiceApproved
 *     }
 *
 * @example
 *     {
 *         disabled: true,
 *         additionalRoles: [],
 *         type: Mercoa.NotificationType.InvoiceApproved
 *     }
 */
export interface NotificationPolicyResponse {
    /** True if the selected notification type is disabled for this entity */
    disabled: boolean;
    /** List of user roles that should receive notifications in addition to the default users for this notification type */
    additionalRoles: string[];
    type: Mercoa.NotificationType;
}
