/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface TokenGenerationPagesOptions {
    paymentMethods?: boolean;
    representatives?: boolean;
    notifications?: boolean;
}
