/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Mercoa from "../../../../api/index";
import * as core from "../../../../core";
import { ProcessPaymentGatewayCardDetails } from "./ProcessPaymentGatewayCardDetails";

export const ProcessPaymentGatewayRequestDocument: core.serialization.ObjectSchema<
    serializers.ProcessPaymentGatewayRequestDocument.Raw,
    Mercoa.ProcessPaymentGatewayRequestDocument
> = core.serialization.object({
    document: core.serialization.string(),
    cardDetails: ProcessPaymentGatewayCardDetails,
});

export declare namespace ProcessPaymentGatewayRequestDocument {
    export interface Raw {
        document: string;
        cardDetails: ProcessPaymentGatewayCardDetails.Raw;
    }
}
