/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Mercoa from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { EphemeralKeyEndpoint } from "./EphemeralKeyEndpoint.js";
import { ProcessPaymentGatewayCardDetailsBase } from "./ProcessPaymentGatewayCardDetailsBase.js";

export const ProcessPaymentGatewayCardDetailsStripeIssuing: core.serialization.ObjectSchema<
    serializers.ProcessPaymentGatewayCardDetailsStripeIssuing.Raw,
    Mercoa.ProcessPaymentGatewayCardDetailsStripeIssuing
> = core.serialization
    .object({
        stripeCardId: core.serialization.string(),
        stripePublishableKey: core.serialization.string(),
        stripeAccountId: core.serialization.string().optional(),
        ephemeralKeyEndpoint: EphemeralKeyEndpoint,
    })
    .extend(ProcessPaymentGatewayCardDetailsBase);

export declare namespace ProcessPaymentGatewayCardDetailsStripeIssuing {
    export interface Raw extends ProcessPaymentGatewayCardDetailsBase.Raw {
        stripeCardId: string;
        stripePublishableKey: string;
        stripeAccountId?: string | null;
        ephemeralKeyEndpoint: EphemeralKeyEndpoint.Raw;
    }
}
