/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Mercoa from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { ValidatePaymentGatewayCardAcceptance } from "./ValidatePaymentGatewayCardAcceptance.js";
import { ValidatePaymentGatewayCardFee } from "./ValidatePaymentGatewayCardFee.js";

export const ValidatePaymentGatewayCardResponse: core.serialization.ObjectSchema<
    serializers.ValidatePaymentGatewayCardResponse.Raw,
    Mercoa.ValidatePaymentGatewayCardResponse
> = core.serialization.object({
    eligibility: ValidatePaymentGatewayCardAcceptance,
    fee: ValidatePaymentGatewayCardFee,
});

export declare namespace ValidatePaymentGatewayCardResponse {
    export interface Raw {
        eligibility: ValidatePaymentGatewayCardAcceptance.Raw;
        fee: ValidatePaymentGatewayCardFee.Raw;
    }
}
