/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Mercoa from "../../../../../../../..";

export interface EntityGetNotificationsRequest {
    /**
     * Start date for notification created on date filter.
     */
    startDate?: Date;
    /**
     * End date for notification created date filter.
     */
    endDate?: Date;
    /**
     * Direction to order notifications by. Defaults to asc.
     */
    orderDirection?: Mercoa.OrderDirection;
    /**
     * Number of invoices to return. Limit can range between 1 and 100, and the default is 10.
     */
    limit?: number;
    /**
     * The ID of the notification to start after. If not provided, the first page of invoices will be returned.
     */
    startingAfter?: Mercoa.NotificationId;
    /**
     * The type of notification to filter by.
     */
    notificationType?: Mercoa.NotificationType | Mercoa.NotificationType[];
}
