/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Mercoa from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const EmailLogAttachment: core.serialization.ObjectSchema<
    serializers.EmailLogAttachment.Raw,
    Mercoa.EmailLogAttachment
> = core.serialization.object({
    filename: core.serialization.string(),
    contentType: core.serialization.string(),
});

export declare namespace EmailLogAttachment {
    export interface Raw {
        filename: string;
        contentType: string;
    }
}
