/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Mercoa from "../../../../api/index";
import * as core from "../../../../core";
import { OcrJobId } from "./OcrJobId";
import { InvoiceResponse } from "../../invoiceTypes/types/InvoiceResponse";
import { CounterpartyResponse } from "../../entityTypes/types/CounterpartyResponse";
import { CheckResponse } from "../../paymentMethodTypes/types/CheckResponse";
import { BankAccountResponse } from "../../paymentMethodTypes/types/BankAccountResponse";

export const OcrResponse: core.serialization.ObjectSchema<serializers.OcrResponse.Raw, Mercoa.OcrResponse> =
    core.serialization.object({
        jobId: OcrJobId,
        invoice: InvoiceResponse,
        vendor: CounterpartyResponse,
        check: CheckResponse.optional(),
        bankAccount: BankAccountResponse.optional(),
    });

export declare namespace OcrResponse {
    interface Raw {
        jobId: OcrJobId.Raw;
        invoice: InvoiceResponse.Raw;
        vendor: CounterpartyResponse.Raw;
        check?: CheckResponse.Raw | null;
        bankAccount?: BankAccountResponse.Raw | null;
    }
}
