/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Mercoa from "../../../../api/index";
import * as core from "../../../../core";
import { EmailSenderProvider } from "./EmailSenderProvider";

export const EmailSenderRequest: core.serialization.ObjectSchema<
    serializers.EmailSenderRequest.Raw,
    Mercoa.EmailSenderRequest
> = core.serialization.object({
    provider: EmailSenderProvider,
    fromEmail: core.serialization.string(),
    fromName: core.serialization.string(),
    apiKey: core.serialization.string().optional(),
});

export declare namespace EmailSenderRequest {
    interface Raw {
        provider: EmailSenderProvider.Raw;
        fromEmail: string;
        fromName: string;
        apiKey?: string | null;
    }
}
