/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Mercoa from "../../../../api";
import * as core from "../../../../core";

export const InvoiceNotificationConfigurationResponse: core.serialization.ObjectSchema<
    serializers.InvoiceNotificationConfigurationResponse.Raw,
    Mercoa.InvoiceNotificationConfigurationResponse
> = core.serialization
    .object({
        type: core.serialization.lazy(async () => (await import("../../..")).NotificationType),
    })
    .extend(
        core.serialization.lazyObject(async () => (await import("../../..")).InvoiceNotificationConfigurationRequest)
    );

export declare namespace InvoiceNotificationConfigurationResponse {
    interface Raw extends serializers.InvoiceNotificationConfigurationRequest.Raw {
        type: serializers.NotificationType.Raw;
    }
}
