/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Mercoa from "../../../../api/index";
import * as core from "../../../../core";
import { EntityId } from "./EntityId";
import { CounterpartyCustomizationAccount } from "./CounterpartyCustomizationAccount";

export const CounterpartyCustomizationRequest: core.serialization.ObjectSchema<
    serializers.CounterpartyCustomizationRequest.Raw,
    Mercoa.CounterpartyCustomizationRequest
> = core.serialization.object({
    counterpartyId: EntityId,
    accounts: core.serialization.list(CounterpartyCustomizationAccount).optional(),
});

export declare namespace CounterpartyCustomizationRequest {
    export interface Raw {
        counterpartyId: EntityId.Raw;
        accounts?: CounterpartyCustomizationAccount.Raw[] | null;
    }
}
