/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Mercoa from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { InvoiceStatus } from "../../invoiceTypes/types/InvoiceStatus.js";

export const CounterpartyInvoiceMetricsStatusResponse: core.serialization.ObjectSchema<
    serializers.CounterpartyInvoiceMetricsStatusResponse.Raw,
    Mercoa.CounterpartyInvoiceMetricsStatusResponse
> = core.serialization.object({
    status: InvoiceStatus,
    totalCount: core.serialization.number(),
    totalAmount: core.serialization.number(),
});

export declare namespace CounterpartyInvoiceMetricsStatusResponse {
    export interface Raw {
        status: InvoiceStatus.Raw;
        totalCount: number;
        totalAmount: number;
    }
}
