/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Mercoa from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const EntityId: core.serialization.Schema<serializers.EntityId.Raw, Mercoa.EntityId> =
    core.serialization.string();

export declare namespace EntityId {
    export type Raw = string;
}
