/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Mercoa from "../../../../api/index";
import * as core from "../../../../core";
import { EntityEventId } from "./EntityEventId";
import { EntityResponse } from "./EntityResponse";
import { EntityUserId } from "./EntityUserId";
import { EntityId } from "./EntityId";

export const EntityEvent: core.serialization.ObjectSchema<serializers.EntityEvent.Raw, Mercoa.EntityEvent> =
    core.serialization.object({
        id: EntityEventId,
        data: EntityResponse,
        webhookIds: core.serialization.list(core.serialization.string()),
        userId: EntityUserId.optional(),
        updatedByEntityId: EntityId.optional(),
        createdAt: core.serialization.date(),
    });

export declare namespace EntityEvent {
    export interface Raw {
        id: EntityEventId.Raw;
        data: EntityResponse.Raw;
        webhookIds: string[];
        userId?: EntityUserId.Raw | null;
        updatedByEntityId?: EntityId.Raw | null;
        createdAt: string;
    }
}
