/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Mercoa from "../../../../api/index";
import * as core from "../../../../core";
import { EntityId } from "./EntityId";

export const EntityAddPayeesRequest: core.serialization.ObjectSchema<
    serializers.EntityAddPayeesRequest.Raw,
    Mercoa.EntityAddPayeesRequest
> = core.serialization.object({
    payees: core.serialization.list(EntityId),
});

export declare namespace EntityAddPayeesRequest {
    interface Raw {
        payees: EntityId.Raw[];
    }
}
