/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Mercoa from "../../../../api/index";
import * as core from "../../../../core";
import { NotificationResponse } from "./NotificationResponse";

export const FindNotificationResponse: core.serialization.ObjectSchema<
    serializers.FindNotificationResponse.Raw,
    Mercoa.FindNotificationResponse
> = core.serialization.object({
    count: core.serialization.number(),
    hasMore: core.serialization.boolean(),
    data: core.serialization.list(NotificationResponse),
});

export declare namespace FindNotificationResponse {
    interface Raw {
        count: number;
        hasMore: boolean;
        data: NotificationResponse.Raw[];
    }
}
