/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Mercoa from "../../../../api/index";
import * as core from "../../../../core";

export const NotificationType: core.serialization.Schema<serializers.NotificationType.Raw, Mercoa.NotificationType> =
    core.serialization.enum_([
        "INVOICE_APPROVAL_NEEDED",
        "INVOICE_APPROVED",
        "INVOICE_REJECTED",
        "INVOICE_SCHEDULED",
        "INVOICE_PENDING",
        "INVOICE_PAID",
        "INVOICE_CANCELED",
        "INVOICE_CREATED",
        "INVOICE_EMAILED",
        "INVOICE_FAILED",
        "COUNTERPARTY_ONBOARDING_COMPLETED",
    ]);

export declare namespace NotificationType {
    export type Raw =
        | "INVOICE_APPROVAL_NEEDED"
        | "INVOICE_APPROVED"
        | "INVOICE_REJECTED"
        | "INVOICE_SCHEDULED"
        | "INVOICE_PENDING"
        | "INVOICE_PAID"
        | "INVOICE_CANCELED"
        | "INVOICE_CREATED"
        | "INVOICE_EMAILED"
        | "INVOICE_FAILED"
        | "COUNTERPARTY_ONBOARDING_COMPLETED";
}
