/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Mercoa from "../../../../api/index";
import * as core from "../../../../core";

export const TokenGenerationEntityOptions: core.serialization.ObjectSchema<
    serializers.TokenGenerationEntityOptions.Raw,
    Mercoa.TokenGenerationEntityOptions
> = core.serialization.object({
    enableMercoaPayments: core.serialization.boolean().optional(),
});

export declare namespace TokenGenerationEntityOptions {
    interface Raw {
        enableMercoaPayments?: boolean | null;
    }
}
