/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Mercoa from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const TokenGenerationEntityOptions: core.serialization.ObjectSchema<
    serializers.TokenGenerationEntityOptions.Raw,
    Mercoa.TokenGenerationEntityOptions
> = core.serialization.object({
    enableMercoaPayments: core.serialization.boolean().optional(),
});

export declare namespace TokenGenerationEntityOptions {
    export interface Raw {
        enableMercoaPayments?: boolean | null;
    }
}
