/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Mercoa from "../../..";

export interface CardBaseResponse {
    id: Mercoa.PaymentMethodId;
    cardType: Mercoa.CardType;
    cardBrand: Mercoa.CardBrand;
    lastFour: string;
    expMonth: string;
    expYear: string;
    supportedCurrencies: Mercoa.CurrencyCode[];
    createdAt: Date;
    updatedAt: Date;
}
