/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Mercoa from "../../..";

export interface CustomPaymentMethodSchemaRequest {
    name: string;
    /** This payment method can be used as a payment source for an invoice */
    isSource: boolean;
    /** This payment method can be used as a payment destination for an invoice */
    isDestination: boolean;
    /** List of currencies that this payment method supports. If not provided, the payment method will support only USD. */
    supportedCurrencies?: Mercoa.CurrencyCode[];
    fields: Mercoa.CustomPaymentMethodSchemaField[];
}
