/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Mercoa from "../../../index";

/**
 * @example
 *     {
 *         foreignId: "DB_FOREIGN_ID",
 *         accountName: "Vendor Wire Account",
 *         accountNumber: "123456789",
 *         schemaId: "cpms_4794d597-70dc-4fec-b6ec-c5988e759769",
 *         data: {
 *             "bankName": "Chase",
 *             "recipientName": "John Doe",
 *             "routingNumber": "123456789",
 *             "accountNumber": "99988767623"
 *         }
 *     }
 */
export interface CustomPaymentMethodRequest extends Mercoa.PaymentMethodBaseRequest {
    /** ID for this payment method in your system */
    foreignId?: string;
    accountName?: string;
    accountNumber?: string;
    /** The available balance for this payment method. */
    availableBalance?: number;
    /** Payment method schema used for this payment method. Defines the fields that this payment method contains. */
    schemaId: Mercoa.CustomPaymentMethodSchemaId;
    /** Object of key/value pairs that matches the keys in the linked payment method schema. */
    data: Record<string, string>;
}
