/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Mercoa } from "@mercoa/javascript";
import * as core from "../../../../core";

export const ApprovalPolicyUpdateRequest: core.serialization.ObjectSchema<
    serializers.ApprovalPolicyUpdateRequest.Raw,
    Mercoa.ApprovalPolicyUpdateRequest
> = core.serialization.object({
    id: core.serialization.lazy(async () => (await import("../../..")).PolicyId),
    trigger: core.serialization.lazy(async () => (await import("../../..")).Trigger).optional(),
    rule: core.serialization.lazy(async () => (await import("../../..")).Rule).optional(),
    upstreamPolicyId: core.serialization.lazy(async () => (await import("../../..")).PolicyId).optional(),
});

export declare namespace ApprovalPolicyUpdateRequest {
    interface Raw {
        id: serializers.PolicyId.Raw;
        trigger?: serializers.Trigger.Raw | null;
        rule?: serializers.Rule.Raw | null;
        upstreamPolicyId?: serializers.PolicyId.Raw | null;
    }
}
