/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         document: "string"
 *     }
 */
export interface UploadDocumentRequest {
    /** Base64 encoded image or PDF of invoice document. PNG, JPG, and PDF are supported. 10MB max. */
    document?: string;
}
