/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Mercoa from "../../../../api/index";
import * as core from "../../../../core";
import { TransactionResponse } from "../../transaction/types/TransactionResponse";

export const TransactionWebhook: core.serialization.ObjectSchema<
    serializers.TransactionWebhook.Raw,
    Mercoa.TransactionWebhook
> = core.serialization.object({
    eventType: core.serialization.string(),
    transaction: TransactionResponse,
});

export declare namespace TransactionWebhook {
    interface Raw {
        eventType: string;
        transaction: TransactionResponse.Raw;
    }
}
