/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Mercoa from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const EntityGroupId: core.serialization.Schema<serializers.EntityGroupId.Raw, Mercoa.EntityGroupId> =
    core.serialization.string();

export declare namespace EntityGroupId {
    export type Raw = string;
}
