/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Mercoa from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { EntityId } from "../../entityTypes/types/EntityId.js";

export const EntityGroupUserEntityRequest: core.serialization.ObjectSchema<
    serializers.EntityGroupUserEntityRequest.Raw,
    Mercoa.EntityGroupUserEntityRequest
> = core.serialization.object({
    roles: core.serialization.list(core.serialization.string()),
    entityId: EntityId,
});

export declare namespace EntityGroupUserEntityRequest {
    export interface Raw {
        roles: string[];
        entityId: EntityId.Raw;
    }
}
