/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Mercoa from "../../../../api/index";
import * as core from "../../../../core";
import { EntityGroupId } from "./EntityGroupId";
import { EntityResponse } from "../../entityTypes/types/EntityResponse";

export const EntityGroupResponse: core.serialization.ObjectSchema<
    serializers.EntityGroupResponse.Raw,
    Mercoa.EntityGroupResponse
> = core.serialization.object({
    id: EntityGroupId,
    foreignId: core.serialization.string().optional(),
    name: core.serialization.string().optional(),
    emailToName: core.serialization.string().optional(),
    entities: core.serialization.list(EntityResponse),
});

export declare namespace EntityGroupResponse {
    interface Raw {
        id: EntityGroupId.Raw;
        foreignId?: string | null;
        name?: string | null;
        emailToName?: string | null;
        entities: EntityResponse.Raw[];
    }
}
