/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type InvoiceStatus =
    | "DRAFT"
    | "NEW"
    | "PENDING"
    | "PAID"
    | "CANCELED"
    | "REFUSED"
    | "APPROVED"
    | "ARCHIVED"
    | "SCHEDULED";

export const InvoiceStatus = {
    Draft: "DRAFT",
    New: "NEW",
    Pending: "PENDING",
    Paid: "PAID",
    Canceled: "CANCELED",
    Refused: "REFUSED",
    Approved: "APPROVED",
    Archived: "ARCHIVED",
    Scheduled: "SCHEDULED",
} as const;
