/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index.js";
import * as Mercoa from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";

export const CodatCompanyResponse: core.serialization.ObjectSchema<
    serializers.entity.CodatCompanyResponse.Raw,
    Mercoa.entity.CodatCompanyResponse
> = core.serialization.object({
    companyId: core.serialization.string(),
});

export declare namespace CodatCompanyResponse {
    export interface Raw {
        companyId: string;
    }
}
