/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as Mercoa from "../../../../../../api";
import * as core from "../../../../../../core";

export const ExternalAccountingSystemCompanyResponse: core.serialization.Schema<
    serializers.entity.ExternalAccountingSystemCompanyResponse.Raw,
    Mercoa.entity.ExternalAccountingSystemCompanyResponse
> = core.serialization
    .union("type", {
        codat: core.serialization.lazyObject(async () => (await import("../../../../..")).entity.CodatCompanyResponse),
    })
    .transform<Mercoa.entity.ExternalAccountingSystemCompanyResponse>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace ExternalAccountingSystemCompanyResponse {
    type Raw = ExternalAccountingSystemCompanyResponse.Codat;

    interface Codat extends serializers.entity.CodatCompanyResponse.Raw {
        type: "codat";
    }
}
