/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as Mercoa from "../../../../../../api";
import * as core from "../../../../../../core";

export const CounterpartyResponse: core.serialization.ObjectSchema<
    serializers.entity.CounterpartyResponse.Raw,
    Mercoa.entity.CounterpartyResponse
> = core.serialization
    .object({
        paymentMethods: core.serialization.list(
            core.serialization.lazy(async () => (await import("../../../../..")).PaymentMethodResponse)
        ),
    })
    .extend(core.serialization.lazyObject(async () => (await import("../../../../..")).entity.EntityResponse));

export declare namespace CounterpartyResponse {
    interface Raw extends serializers.entity.EntityResponse.Raw {
        paymentMethods: serializers.PaymentMethodResponse.Raw[];
    }
}
