/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Mercoa from "../../../../..";

export interface ApprovalRequest {
    /** Comment associated with this approval action. */
    text?: string;
    userId: Mercoa.EntityUserId;
}
