/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index.js";
import * as Mercoa from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";

export const InvalidateTokensRequest: core.serialization.Schema<
    serializers.organization.InvalidateTokensRequest.Raw,
    Mercoa.organization.InvalidateTokensRequest
> = core.serialization.object({
    sessionId: core.serialization.list(core.serialization.string()).optional(),
});

export declare namespace InvalidateTokensRequest {
    export interface Raw {
        sessionId?: string[] | null;
    }
}
