/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Mercoa from "../../../index";

/**
 * @example
 *     {
 *         vendorNetwork: Mercoa.VendorNetwork.Entity,
 *         entityId: "entity_8f86116b-3b4d-4ded-99ef-3bc929d8c33c",
 *         mimeType: "image/png",
 *         image: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAIAQMAAAD+wSzIAAAABlBMVEX///+/v7+jQ3Y5AAAADklEQVQI12P4AIX8EAgALgAD/aNpbtEAAAAASUVORK5CYII"
 *     }
 */
export interface OcrRequest {
    /** MIME type of the image. Supported types are image/png, image/jpeg, and application/pdf. */
    mimeType: string;
    /** Base64 encoded image or PDF. PNG, JPG, WEBP, and PDF are supported. 10MB max. */
    image: string;
    /** Limit OCR vendor search to a specific network */
    vendorNetwork?: Mercoa.VendorNetwork;
    /** When using the Entity vendor network, specify the entity to use if. EntityId on an auth token will take precedence over this parameter. */
    entityId?: Mercoa.EntityId;
}
