/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type VendorNetwork = "ENTITY" | "PLATFORM" | "MERCOA";

export const VendorNetwork = {
    Entity: "ENTITY",
    Platform: "PLATFORM",
    Mercoa: "MERCOA",
} as const;
