/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         addressLine1: "123 Main St",
 *         addressLine2: "Unit 1",
 *         city: "San Francisco",
 *         stateOrProvince: "CA",
 *         postalCode: "94105",
 *         country: "US"
 *     }
 *
 * @example
 *     {
 *         addressLine1: "456 Main St",
 *         city: "New York",
 *         stateOrProvince: "NY",
 *         postalCode: "10001",
 *         country: "US"
 *     }
 */
export interface Address {
    addressLine1: string;
    addressLine2?: string;
    city: string;
    /** State or province code. Must be in the format XX. */
    stateOrProvince: string;
    postalCode: string;
    country?: string;
}
