/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         ssn: "123-45-6789"
 *     }
 *
 * @example
 *     {
 *         ssn: "987-65-4321"
 *     }
 */
export interface IndividualGovernmentId {
    /** Full Social Security Number. Must be in the format 123-45-6789. */
    ssn: string;
}
