/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Mercoa from "../../../index";

/**
 * @example
 *     {
 *         firstName: "John",
 *         lastName: "Doe",
 *         postalCode: "12345",
 *         country: Mercoa.CountryCode.Us,
 *         iframeUrl: "https://www.myvirtualcard.com/iframe/345345"
 *     }
 */
export interface ProcessPaymentGatewayCardDetailsIframe extends Mercoa.ProcessPaymentGatewayCardDetailsBase {
    /** The URL of the iframe that render the virtual card details */
    iframeUrl: string;
}
