/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Mercoa from "../../../index.js";

/**
 * @example
 *     {
 *         firstName: "John",
 *         lastName: "Doe",
 *         postalCode: "12345",
 *         country: Mercoa.CountryCode.Us,
 *         cardType: Mercoa.ProcessPaymentGatewayCardType.Credit,
 *         embedRequest: "eyJ0b2tlbiI6InNhbXBsZV90b2tlbiIsImNzcyI6Imh0dHBzOi8vc3RvcmFnZS5nb29nbGVhcGlzLmNvbS9tZXJjb2EtcGFydG5lci1sb2dvcy9saXRoaWMuY3NzIn0=",
 *         hmac: "abc123def456ghi789",
 *         achDetails: {
 *             routingNumber: "123456789",
 *             accountNumber: "987654321",
 *             accountName: "John Doe"
 *         }
 *     }
 */
export interface ProcessPaymentGatewayCardDetailsLithic extends Mercoa.ProcessPaymentGatewayCardDetailsBase {
    /** The base64-encoded embed request for the Lithic virtual card */
    embedRequest: string;
    /** The HMAC signature for the embed request */
    hmac: string;
}
