/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Mercoa from "../../../index.js";

/**
 * @example
 *     {
 *         routingNumber: "123456789",
 *         accountNumber: "987654321",
 *         accountName: "John Doe",
 *         accountType: Mercoa.BankType.Checking
 *     }
 */
export interface ProcessPaymentGatewayAchDetails {
    /** The routing number of the ACH account */
    routingNumber: string;
    /** The account number of the ACH account */
    accountNumber: string;
    /** The name on the ACH account */
    accountName?: string;
    /** The type of bank account (checking or savings) */
    accountType?: Mercoa.BankType;
}
