/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ProcessPaymentGatewayPendingResponse {
    /** The job ID of the payment gateway processing job */
    jobId: string;
    /** The timestamp when the job was created */
    createdAt: Date;
    /** The timestamp when the job was last updated */
    updatedAt: Date;
}
