/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Mercoa from "../../../index";

/**
 * @example
 *     {
 *         jobStatus: "pending",
 *         jobId: "pgv_8f86116b-3b4d-4ded-99ef-3bc929d8c33c",
 *         createdAt: "2024-01-01T00:00:00Z",
 *         updatedAt: "2024-01-01T00:00:00Z"
 *     }
 *
 * @example
 *     {
 *         jobStatus: "success",
 *         jobId: "pgv_8f86116b-3b4d-4ded-99ef-3bc929d8c33c",
 *         paymentGatewayUrl: "https://www.payment-gateway.com/invoice/pgv_8f86116b-3b4d-4ded-99ef-3bc929d8c33c",
 *         sessionUrl: "https://www.payment-gateway.com/session/pgv_8f86116b-3b4d-4ded-99ef-3bc929d8c33c",
 *         card: {
 *             eligibility: Mercoa.ValidatePaymentGatewayCardAcceptance.Accepted,
 *             fee: {
 *                 type: "percentage",
 *                 value: 2.5
 *             }
 *         },
 *         createdAt: "2024-01-01T00:00:00Z",
 *         updatedAt: "2024-01-01T00:00:00Z"
 *     }
 *
 * @example
 *     {
 *         jobStatus: "failed",
 *         jobId: "pgv_8f86116b-3b4d-4ded-99ef-3bc929d8c33c",
 *         errorType: Mercoa.PaymentGatewayError.NoValidPaymentGatewayFound,
 *         errorMessage: "No valid payment gateway was found in the document or HTML",
 *         createdAt: "2024-01-01T00:00:00Z",
 *         updatedAt: "2024-01-01T00:00:00Z"
 *     }
 */
export type ValidatePaymentGatewayResponse =
    | Mercoa.ValidatePaymentGatewayResponse.Pending
    | Mercoa.ValidatePaymentGatewayResponse.Success
    | Mercoa.ValidatePaymentGatewayResponse.Failed;

export namespace ValidatePaymentGatewayResponse {
    export interface Pending extends Mercoa.ValidatePaymentGatewayPendingResponse {
        jobStatus: "pending";
    }

    export interface Success extends Mercoa.ValidatePaymentGatewaySuccessResponse {
        jobStatus: "success";
    }

    export interface Failed extends Mercoa.ValidatePaymentGatewayFailedResponse {
        jobStatus: "failed";
    }
}
