/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         value: 250
 *     }
 */
export interface ValidatePaymentGatewayCardFeePercentage {
    /** The fee percentage in bps. For example, if the fee is 2.5% and the payment amount is $100, set this to 250. */
    value: number;
}
