/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Mercoa from "../../../index";

/**
 * @example
 *     {
 *         type: "document",
 *         document: "ValidatePaymentGatewayRequestDocument.Default"
 *     }
 *
 * @example
 *     {
 *         type: "html",
 *         html: "ValidatePaymentGatewayRequestHTML.Default"
 *     }
 */
export type ValidatePaymentGatewayRequest =
    | Mercoa.ValidatePaymentGatewayRequest.Document
    | Mercoa.ValidatePaymentGatewayRequest.Html;

export namespace ValidatePaymentGatewayRequest {
    export interface Document extends Mercoa.ValidatePaymentGatewayRequestDocument {
        type: "document";
    }

    export interface Html extends Mercoa.ValidatePaymentGatewayRequestHtml {
        type: "html";
    }
}
