/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Mercoa } from "@mercoa/javascript";

export interface InvoiceMetricsRequest {
    /**
     * Invoice status to filter on
     */
    status?: Mercoa.InvoiceStatus | Mercoa.InvoiceStatus[];
    /**
     * Start date for invoice dueDate filter.
     */
    dueDateStart?: Date;
    /**
     * End date for invoice dueDate filter.
     */
    dueDateEnd?: Date;
    /**
     * Start date for invoice created on date filter.
     */
    createdDateStart?: Date;
    /**
     * End date for invoice created date filter.
     */
    createdDateEnd?: Date;
    /**
     * Currency to filter on
     */
    currency: Mercoa.CurrencyCode;
}
