/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Mercoa from "../../../../api/index";
import * as core from "../../../../core";

export const DocumentType: core.serialization.Schema<serializers.DocumentType.Raw, Mercoa.DocumentType> =
    core.serialization.enum_([
        "INVOICE",
        "PAYMENT_CONFIRMATION",
        "TEN_NINETY_NINE",
        "W9",
        "CHECK",
        "BANK_STATEMENT",
        "CONTRACT",
        "OTHER",
    ]);

export declare namespace DocumentType {
    export type Raw =
        | "INVOICE"
        | "PAYMENT_CONFIRMATION"
        | "TEN_NINETY_NINE"
        | "W9"
        | "CHECK"
        | "BANK_STATEMENT"
        | "CONTRACT"
        | "OTHER";
}
