/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Mercoa from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const IndividualGovernmentId: core.serialization.ObjectSchema<
    serializers.IndividualGovernmentId.Raw,
    Mercoa.IndividualGovernmentId
> = core.serialization.object({
    ssn: core.serialization.string(),
});

export declare namespace IndividualGovernmentId {
    export interface Raw {
        ssn: string;
    }
}
