/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as Mercoa from "../../../../../../api";
import * as core from "../../../../../../core";

export const ApprovalPolicyRequest: core.serialization.ObjectSchema<
    serializers.entity.ApprovalPolicyRequest.Raw,
    Mercoa.entity.ApprovalPolicyRequest
> = core.serialization.object({
    trigger: core.serialization.lazy(async () => (await import("../../../../..")).entity.Trigger),
    rule: core.serialization.lazy(async () => (await import("../../../../..")).entity.Rule),
    upstreamPolicyId: core.serialization.lazy(async () => (await import("../../../../..")).ApprovalPolicyId),
});

export declare namespace ApprovalPolicyRequest {
    interface Raw {
        trigger: serializers.entity.Trigger.Raw;
        rule: serializers.entity.Rule.Raw;
        upstreamPolicyId: serializers.ApprovalPolicyId.Raw;
    }
}
